### ISSUE TITLE
Error messages when plotting

### ISSUE THREAD

**Issue by aegerton** [context-dependent/tidy-tuesday#1]
I received the following error message when trying to replicate the plot;-
```
Error in scale_colour_viridis_d() : 
  could not find function "scale_colour_viridis_d"
```
I replaced 'scale_colour_virids_d' with 'scale_colour_viridis', but received another error message:-
```
Error: Discrete value supplied to continuous scale
In addition: Warning message:
Width not defined. Set with `position_dodge(width = ?)`
```
What am I doing wrong, please?

**Comment by context-dependent** [comment]
Hey sorry to leave you hanging. The convenience functions scale_colour_viridis_d (discrete) and _c (continuous) are included in the dev version of ggplot2 for sure, and possibly also the latest cran release. Try running `install.packages("ggplot2")` and if that doesnt work, try `devtools::install_github("tidyverse/ggplot2")`

**Comment by context-dependent** [comment]
Hey sorry to leave you hanging. The convenience functions scale_colour_viridis_d (discrete) and _c (continuous) are included in the dev version of ggplot2 for sure, and possibly also the latest cran release. Try running `install.packages("ggplot2")` and if that doesnt work, try `devtools::install_github("tidyverse/ggplot2")`
